Repository MarcBrout/HQSE_2, pull requests merged in 2019-11, with the labels that each got.

#7 Add changelog
  CHANGELOG.md
Labels: documentation

#9 added travis statuses
  README.md
Labels: documentation

#11 remove build folder
  .gitignore
  build/libs/chatbot.jar
  build/tmp/fatJar/MANIFEST.MF
  build/tmp/jar/MANIFEST.MF
Labels: chore

#12 simplified checkstyle
  config/checkstyle/checkstyle.xml
Labels: chore

#14 feat(user&date): add user and date classes and tests
  src/main/java/utils/CurrentDate.java
  src/main/java/utils/User.java
  src/test/java/CurrentDateTest.java
  src/test/java/UserTest.java
Labels: enhancement

#13 feat(bot): add bot class and tests
  src/main/java/Bot.java
  src/test/java/BotTest.java
Labels: enhancement

#15 feature(bot): adding message with date from bot
  src/main/java/Bot.java
Labels: enhancement

#16 Add argugment parsing
  config/checkstyle/checkstyle.xml
  src/main/java/parsing/CommandLine.java
  src/main/java/parsing/Option.java
  src/test/java/parsing/CommandLineTest.java
  src/test/java/parsing/OptionTest.java
Labels: enhancement

#17 fix(scanner): resolve scanner issue due to ide console
  src/main/java/Bot.java
  src/main/java/Main.java
  src/main/java/Room.java
Labels: enhancement

#18 setup build
  build.gradle
  settings.gradle
  src/main/java/Main.java
  src/main/java/Room.java
  src/main/java/parsing/Option.java
Labels: enhancement
